version: '3'
services:
  db:
    image: postgres
    container_name: web_game_db
    env_file:
      - .app.env
    ports:
      - "5432:5432"
  app:
    build: .
    image: web_game:latest
    container_name: web_game_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/web_game
    env_file:
      - .app.env
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    #command: puma
    # sudo chown -R $USER:$USER .